package th.co.cbank.project.model;

import java.util.Date;
import lombok.Data;

@Data
public class BranchBean {

    private String Code = "";
    private String Name = "";
    private String AddressNo;
    private String Locality;
    private String SubProvince;
    private String Province;
    private String Post;
    private String Tel_No;
    private String Fax_No;
    private String E_Mail;
    private String Manager;
    private String Location_Area;
    private double Ser_Area = 0.00;
    private double Cou_Area = 0.00;
    private double Kic_Area = 0.00;
    private double Tot_Area = 0.00;
    private double Cost = 0.00;
    private double Charge = 0.00;
    private String FlageCost = "N";
    private double Gp = 0.00;
    private String FlageGp = "N";
    private String Remark;
    private double ArBillNo = 1;
    private double EarneatBillNo = 1;
    private double ReturnBillNo = 1;
    private Date PrintAutoSumDate;
    private String SaveOrder = "N";
    private String SaveOrderCopy = "N";
    private String SaveOrderChk = "N";
    private String KIC1 = "N";
    private String KIC2 = "N";
    private String KIC3 = "N";
    private String KIC4 = "N";
    private String KIC5 = "N";
    private String KIC6 = "N";
    private String KIC7 = "N";
    private String KIC8 = "N";
    private String KIC9 = "N";
    private String SmartCard = "N";
    private String GetFile;
    private String RetFile;
    private String PointFile;
    private int CntLoop = 1;
    private double InvNo = 1;
    private double InvCashNo = 1;
    private double InvCash = 1;
    private String InvActive = "Y";
    private String CreditAct;
    private String PromotionGP;
    private int LockTime = 0;
    private int KicItemNo = 0;
    private String PT1;
    private String PT2;
    private String PT3;
    private String PT4;
    private String PT5;
    private int PONO = 1;
    private String PrintKicForm = "1";
    private String PrintInvForm = "1";
    private String PSelectStk = "P";
    private String PStkChk = "N";
    private String PMinStkChk = "N";
    private double RoundUpTime = 0;
    private String GiftStatusChk = "N";
    private String KICCopy1 = "1";
    private String KICCopy2 = "1";
    private String KICCopy3 = "1";
    private String KICCopy4 = "1";
    private String KICCopy5 = "1";
    private String KICCopy6 = "1";
    private String KICCopy7 = "1";
    private String KICCopy8 = "1";
    private String KICCopy9 = "1";
    private String KICChk1 = "N";
    private String KICChk2 = "N";
    private String KICChk3 = "N";
    private String KICChk4 = "N";
    private String KICChk5 = "N";
    private String KICChk6 = "N";
    private String KICChk7 = "N";
    private String KICChk8 = "N";
    private String KICChk9 = "N";
    private String UpdateBranchPoint = "Y";

}
